import*as S from'./state.js';
import{PROC_COLORS}from'./constants.js';
import{fD,esc,statusBadge}from'./utils.js';
import{db,doc,addDoc,collection,serverTimestamp,writeBatch,deleteDoc}from'./firebase.js';

export function renderCalendar(){
const today=fD(new Date());
if(S.calView==='issues'){document.getElementById('calTitle').textContent='이슈 보드';renderIssueBoard();return;}
if(S.calView==='week'){const dow=S.calDate.getDay();const mon=new Date(S.calDate);mon.setDate(S.calDate.getDate()-(dow===0?6:dow-1));const fri=new Date(mon);fri.setDate(mon.getDate()+4);document.getElementById('calTitle').textContent=`${fD(mon)} ~ ${fD(fri)}`;renderWeekCal(mon);return;}
document.getElementById('calTitle').textContent=`${S.calDate.getFullYear()}년 ${S.calDate.getMonth()+1}월`;renderMonthCal();
}

function renderMonthCal(){const y=S.calDate.getFullYear(),m=S.calDate.getMonth();const firstDay=new Date(y,m,1).getDay();const dim=new Date(y,m+1,0).getDate();const today=fD(new Date());let html=`<div class="cal-grid">`;['일','월','화','수','목','금','토'].forEach(d=>html+=`<div class="cal-header-cell">${d}</div>`);let day=1;for(let i=0;i<6;i++){for(let j=0;j<7;j++){const idx=i*7+j;if(idx<firstDay||day>dim){html+=`<div class="cal-cell other-month"></div>`;}else{const ds=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;const isToday=ds===today;const hasIssue=S.ISSUES.some(is=>is.date===ds);const endProcs=[];S.D.forEach(item=>{const procs=item.processes||{};(item.route||'').split('→').filter(Boolean).forEach(p=>{const proc=procs[p]||{};if(proc.planEnd===ds)endProcs.push({sn:item.sn,proc:p,status:proc.status});});});let bars='';endProcs.slice(0,2).forEach(e=>{const c=PROC_COLORS[e.proc]||'#666';bars+=`<div class="cal-bar" style="background:${c}22;color:${c}">📍 ${e.sn?.slice(-6)} ${e.proc}</div>`;});html+=`<div class="cal-cell${isToday?' today':''}" onclick="showCalDayDetail('${ds}')">${hasIssue?'<div class="cal-issue-dot"></div>':''}<div class="cal-day" style="${isToday?'color:var(--ac2);':''}">${day}</div>${bars}${endProcs.length>2?`<div style="font-size:9px;color:var(--t2)">+${endProcs.length-2}건</div>`:''}</div>`;day++;}}if(day>dim)break;}html+='</div>';document.getElementById('calContent').innerHTML=html;}

function renderWeekCal(monday){const today=fD(new Date());let html=`<div style="display:grid;grid-template-columns:repeat(5,1fr);gap:1px;background:var(--border);border-radius:var(--r2);overflow:hidden">`;for(let i=0;i<5;i++){const d=new Date(monday);d.setDate(monday.getDate()+i);const ds=fD(d);const isToday=ds===today;const endProcs=[];S.D.forEach(item=>{const procs=item.processes||{};(item.route||'').split('→').filter(Boolean).forEach(p=>{const proc=procs[p]||{};if(proc.planEnd===ds)endProcs.push({sn:item.sn,proc:p,status:proc.status});});});const hasIssue=S.ISSUES.some(is=>is.date===ds);html+=`<div style="background:var(--bg3);min-height:120px;padding:8px;cursor:pointer;position:relative${isToday?';border:1px solid var(--ac1)':''}" onclick="showCalDayDetail('${ds}')">${hasIssue?'<div class="cal-issue-dot"></div>':''}<div style="font-size:12px;font-weight:600;margin-bottom:6px${isToday?';color:var(--ac2)':''}">${['월','화','수','목','금'][i]} ${d.getDate()}</div>${endProcs.slice(0,4).map(e=>`<div class="cal-bar" style="background:${PROC_COLORS[e.proc]||'#666'}22;color:${PROC_COLORS[e.proc]||'#666'}">${e.sn?.slice(-6)} ${e.proc}</div>`).join('')}${endProcs.length>4?`<div style="font-size:9px;color:var(--t2)">+${endProcs.length-4}건</div>`:''}</div>`;}html+='</div>';document.getElementById('calContent').innerHTML=html;}

export function showCalDayDetail(ds){const endProcs=[],startProcs=[],inProg=[];S.D.forEach(item=>{const procs=item.processes||{};(item.route||'').split('→').filter(Boolean).forEach(p=>{const proc=procs[p]||{};if(proc.planEnd===ds)endProcs.push({sn:item.sn,proc:p,equip:proc.equip||'',status:proc.status});if(proc.startDate===ds)startProcs.push({sn:item.sn,proc:p,equip:proc.equip||''});if(proc.status==='진행'&&proc.startDate<=ds&&proc.planEnd>=ds)inProg.push({sn:item.sn,proc:p,equip:proc.equip||''});});});const issuesDay=S.ISSUES.filter(is=>is.date===ds);const html=`<div class="card" style="margin-top:12px"><div style="font-size:14px;font-weight:600;margin-bottom:12px">${ds} 상세</div>${endProcs.length?`<div style="margin-bottom:10px"><div class="card-title">📍 완료예정 (${endProcs.length})</div>${endProcs.map(e=>`<div style="font-size:12px;padding:4px 0;display:flex;gap:8px;align-items:center;flex-wrap:wrap"><span style="color:${PROC_COLORS[e.proc]}">${e.proc}</span><span>${e.sn}</span>${statusBadge(e.status)}</div>`).join('')}</div>`:''}${startProcs.length?`<div style="margin-bottom:10px"><div class="card-title">🚀 시작예정 (${startProcs.length})</div>${startProcs.map(e=>`<div style="font-size:12px;padding:4px 0;display:flex;gap:8px"><span style="color:${PROC_COLORS[e.proc]}">${e.proc}</span><span>${e.sn}</span></div>`).join('')}</div>`:''}${inProg.length?`<div style="margin-bottom:10px"><div class="card-title">🔄 진행중 (${inProg.length})</div>${inProg.map(e=>`<div style="font-size:12px;padding:4px 0;display:flex;gap:8px"><span style="color:${PROC_COLORS[e.proc]}">${e.proc}</span><span>${e.sn}</span></div>`).join('')}</div>`:''}${issuesDay.length?`<div><div class="card-title">🚨 이슈 (${issuesDay.length})</div>${issuesDay.map(i=>`<div style="font-size:12px;padding:4px 0">${statusBadge(i.type)} ${i.content}</div>`).join('')}</div>`:''}${!endProcs.length&&!startProcs.length&&!inProg.length&&!issuesDay.length?`<div style="font-size:13px;color:var(--t2);text-align:center;padding:20px">일정 없음</div>`:''}</div>`;if(S.calView==='month')renderMonthCal();document.getElementById('calContent').insertAdjacentHTML('beforeend',html);}

let issuePage=0;const IPP=20;
function renderIssueBoard(){const total=S.ISSUES.length;const pages=Math.ceil(total/IPP);const slice=S.ISSUES.slice(issuePage*IPP,(issuePage+1)*IPP);let html=`<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:12px;flex-wrap:wrap;gap:8px"><strong style="font-size:14px">전체 이슈 ${total}건</strong><div style="display:flex;gap:6px;align-items:center"><button class="btn btn-danger btn-sm" onclick="deleteSelectedIssues()">선택 삭제</button><button class="btn btn-primary btn-sm" onclick="openIssueModal()">+ 이슈등록</button></div></div><div class="table-wrap"><table><thead><tr><th><input type="checkbox" onchange="toggleAllIssues(this)"></th><th>날짜</th><th>유형</th><th class="hide-mobile">제품</th><th class="hide-mobile">S/N</th><th>내용</th><th class="hide-mobile">등록자</th></tr></thead><tbody>${slice.map(is=>`<tr><td><input type="checkbox" class="issue-check" value="${is.id}"></td><td style="font-size:12px">${is.date||''}</td><td>${statusBadge(is.type||'메모')}</td><td class="hide-mobile" style="font-size:12px">${is.productName||''}</td><td class="hide-mobile" style="font-size:11px;font-family:monospace">${is.sn||''}</td><td style="font-size:12px;max-width:200px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${is.content||''}</td><td class="hide-mobile" style="font-size:11px;color:var(--t2)">${(is.createdBy||'').split('@')[0]}</td></tr>`).join('')}</tbody></table></div><div style="display:flex;gap:6px;justify-content:center;margin-top:12px">${Array.from({length:pages},(_,i)=>`<button class="btn ${i===issuePage?'btn-primary':'btn-secondary'} btn-sm" onclick="setIssuePage(${i})">${i+1}</button>`).join('')}</div>`;document.getElementById('calContent').innerHTML=html;}

export function setIssuePage(p){issuePage=p;renderIssueBoard();}
export function toggleAllIssues(cb){document.querySelectorAll('.issue-check').forEach(c=>c.checked=cb.checked);}
export async function deleteSelectedIssues(){const checked=[...document.querySelectorAll('.issue-check:checked')].map(c=>c.value);if(!checked.length){import('./utils.js').then(u=>u.toast('삭제할 이슈를 선택하세요','warn'));return;}if(!confirm(`${checked.length}건 삭제?`))return;const batch=writeBatch(db);checked.forEach(id=>batch.delete(doc(db,'issues',id)));await batch.commit();import('./utils.js').then(u=>u.toast('삭제 완료','ok'));}
export function setCalView(v,btn){S.setCalView(v);document.querySelectorAll('#calendarTab .tab-btn').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');renderCalendar();}
export function calPrev(){if(S.calView==='month')S.calDate.setMonth(S.calDate.getMonth()-1);else if(S.calView==='week')S.calDate.setDate(S.calDate.getDate()-7);renderCalendar();}
export function calNext(){if(S.calView==='month')S.calDate.setMonth(S.calDate.getMonth()+1);else if(S.calView==='week')S.calDate.setDate(S.calDate.getDate()+7);renderCalendar();}
export function calToday(){S.setCalDate(new Date());renderCalendar();}
