import*as S from'./state.js';
import{PROC_COLORS,EQ_MAP}from'./constants.js';
import{fD,buildRoute,procDays,addBD,toast,openModal,closeModal,calcProgress,getDplus}from'./utils.js';
import{db,doc,setDoc,addDoc,getDocs,collection,writeBatch,serverTimestamp,getMaxSeqFromFirestore}from'./firebase.js';

export function openProductModal(){document.getElementById('pm_name').value='';document.getElementById('pm_cat').value='WN';document.getElementById('pm_drawing').value='';document.getElementById('pm_shrink').value='';document.getElementById('pm_stack').value='';document.getElementById('pm_joint').value='Brazing';document.getElementById('pm_heat').value='N';updatePMRoute();openModal('productModal');['pm_cat','pm_joint','pm_heat'].forEach(id=>document.getElementById(id).addEventListener('change',updatePMRoute));}
function updatePMRoute(){document.getElementById('pm_routePreview').textContent=buildRoute(document.getElementById('pm_cat').value,document.getElementById('pm_joint').value,document.getElementById('pm_heat').value);}
export async function saveProduct(){const name=document.getElementById('pm_name').value.trim();if(!name){toast('제품명을 입력하세요','err');return;}const cat=document.getElementById('pm_cat').value;const joint=document.getElementById('pm_joint').value;const heat=document.getElementById('pm_heat').value;const route=buildRoute(cat,joint,heat);await setDoc(doc(db,'products',name),{category:cat,drawingNo:document.getElementById('pm_drawing').value,shrinkage:parseFloat(document.getElementById('pm_shrink').value)||0,stackCount:parseInt(document.getElementById('pm_stack').value)||0,dcJoint:joint,heatTreat:heat,route});const pSnap=await getDocs(collection(db,'products'));S.setPRODS(pSnap.docs.map(d=>({id:d.id,...d.data()})));toast('제품 등록 완료','ok');closeModal('productModal');}

export function openSNModal(){const today=fD(new Date());document.getElementById('sn_start').value=today;document.getElementById('sn_batch').value='';document.getElementById('sn_sheet').value='';document.getElementById('sn_qty').value=1;document.getElementById('sn_seq').value=1;const sel=document.getElementById('sn_prod');sel.innerHTML='<option value="">선택...</option>'+S.PRODS.map(p=>`<option value="${p.id}">${p.id}</option>`).join('');const batches=[...new Set(S.D.map(d=>d.batchId).filter(Boolean))];document.getElementById('batchList').innerHTML=batches.map(b=>`<option value="${b}">`).join('');document.getElementById('equipConflictWarn').innerHTML='';updateSNPreview();openModal('snModal');}

export function autoBatchCode(){const today=fD(new Date()).replace(/-/g,'');const existing=S.D.filter(d=>d.batchId&&d.batchId.startsWith(today)).map(d=>parseInt(d.batchId.split('-')[1]||0));const next=existing.length?Math.max(...existing)+1:1;document.getElementById('sn_batch').value=`${today}-${String(next).padStart(3,'0')}`;updateSNPreview();}

export async function onSNProdChange(){const prodId=document.getElementById('sn_prod').value;if(!prodId)return;const prod=S.PRODS.find(p=>p.id===prodId);if(!prod)return;const cat=prod.category||'WN';const eqs=EQ_MAP['탈지'][cat]||[];document.getElementById('sn_equip').innerHTML=eqs.map(e=>`<option>${e}</option>`).join('');const sheetNo=document.getElementById('sn_sheet').value.trim();const maxSeq=await getMaxSeqFromFirestore(cat,prodId,sheetNo);let nextSeq,hintText;if(maxSeq>=999){nextSeq=1;hintText='⚠️ L999 도달';}else if(maxSeq>0){nextSeq=maxSeq+1;hintText=`현재 최대: L${String(maxSeq).padStart(3,'0')} → 다음: L${String(maxSeq+1).padStart(3,'0')}`;}else{nextSeq=1;hintText='신규 제품';}document.getElementById('sn_seq').value=nextSeq;document.getElementById('sn_seqHint').textContent=hintText;updateSNPreview();checkEquipConflict();}

export async function onSheetNoChange(){const prodId=document.getElementById('sn_prod').value;if(!prodId){updateSNPreview();return;}const prod=S.PRODS.find(p=>p.id===prodId);if(!prod){updateSNPreview();return;}const cat=prod.category||'WN';const sheetNo=document.getElementById('sn_sheet').value.trim();if(sheetNo.length<6){updateSNPreview();return;}const maxSeq=await getMaxSeqFromFirestore(cat,prodId,sheetNo);let nextSeq,hintText;if(maxSeq>=999){nextSeq=1;hintText='⚠️ L999 도달';}else if(maxSeq>0){nextSeq=maxSeq+1;hintText=`현재 최대: L${String(maxSeq).padStart(3,'0')} → 다음: L${String(maxSeq+1).padStart(3,'0')}`;}else{nextSeq=1;hintText='신규 시트번호';}document.getElementById('sn_seq').value=nextSeq;document.getElementById('sn_seqHint').textContent=hintText;updateSNPreview();}

export function updateSNPreview(){const prod=document.getElementById('sn_prod').value;const sheet=document.getElementById('sn_sheet').value||'??????';const qty=parseInt(document.getElementById('sn_qty').value)||1;const seq=parseInt(document.getElementById('sn_seq').value)||1;const cat=S.PRODS.find(p=>p.id===prod)?.category||'??';let html='';for(let i=0;i<Math.min(qty,10);i++){const seqNum=((seq+i-1)%999)+1;html+=`<div>${cat}${sheet}-${prod||'???'}-L${String(seqNum).padStart(3,'0')}</div>`;}if(qty>10)html+=`<div style="color:var(--t2)">... 외 ${qty-10}건</div>`;document.getElementById('sn_preview').innerHTML=html||'미리보기 없음';}

export function checkEquipConflict(){const warnEl=document.getElementById('equipConflictWarn');warnEl.innerHTML='';const equip=document.getElementById('sn_equip').value;const startDate=document.getElementById('sn_start').value;const prodId=document.getElementById('sn_prod').value;if(!equip||!startDate||!prodId)return;const conflicts=S.D.filter(item=>{const p=(item.processes||{})['탈지'];if(!p)return false;if(p.equip!==equip)return false;if(p.status==='완료'||p.status==='폐기')return false;if(p.startDate&&p.planEnd)return p.startDate<=startDate&&p.planEnd>=startDate;return p.startDate===startDate;});if(conflicts.length>0){warnEl.innerHTML=`<div class="equip-conflict-warn">⚠️ 탈지 ${equip}에 이미 ${conflicts.length}건 배정됨: ${conflicts.slice(0,5).map(c=>c.sn).join(', ')}</div>`;}}

export async function saveSNBatch(options){
let batchId,sheetNo,prodId,equip,qty,startDate,seq;
if(options){batchId=options.batchId;sheetNo=options.sheetNo||'';prodId=options.product;equip=options.equipment||'';qty=options.quantity||1;startDate=options.startDate;seq=options.seq||1;}
else{batchId=document.getElementById('sn_batch').value.trim();sheetNo=document.getElementById('sn_sheet').value.trim();prodId=document.getElementById('sn_prod').value;equip=document.getElementById('sn_equip').value;qty=parseInt(document.getElementById('sn_qty').value)||1;startDate=document.getElementById('sn_start').value;seq=parseInt(document.getElementById('sn_seq').value)||1;}
if(!batchId||!prodId||!startDate){toast('필수 항목을 입력하세요','err');return;}
const prod=S.PRODS.find(p=>p.id===prodId);if(!prod){toast('제품을 찾을 수 없습니다','err');return;}
const cat=prod.category;const stack=prod.stackCount||0;const joint=prod.dcJoint||'Brazing';const heat=prod.heatTreat||'N';const routeStr=prod.route||buildRoute(cat,joint,heat);const routeArr=routeStr.split('→').filter(Boolean);
if(!sheetNo)sheetNo=fD(new Date()).replace(/-/g,'').slice(2);
const batch=writeBatch(db);
for(let i=0;i<qty;i++){const seqNum=((seq+i-1)%999)+1;const sn=`${cat}${sheetNo}-${prodId}-L${String(seqNum).padStart(3,'0')}`;const processes={};let cumDays=0;
for(let j=0;j<routeArr.length;j++){const pn=routeArr[j];const days=procDays(pn,cat,stack);const pStart=addBD(new Date(startDate),cumDays);const pEnd=addBD(new Date(pStart),days);processes[pn]={order:j+1,equip:j===0?equip:'',status:'대기',startDate:fD(pStart),planEnd:fD(pEnd),actualEnd:'',planDays:days,actualDays:0,defect:'',remark:''};cumDays+=days;}
const endDate=fD(addBD(new Date(startDate),routeArr.reduce((s,p)=>s+procDays(p,cat,stack),0)));
batch.set(doc(db,'production',sn),{batchId,sn,category:cat,productName:prodId,drawingNo:prod.drawingNo||'',shrinkage:prod.shrinkage||0,stackCount:stack,dcJoint:joint,heatTreat:heat,equipment:equip,currentProcess:routeArr[0]||'',status:'대기',startDate,endDate,progress:0,route:routeStr,sheetNo,registeredAt:fD(new Date()),defectType:'',processes});}
await batch.commit();toast(`${qty}건 S/N 생성 완료`,'ok');if(!options)closeModal('snModal');}

export function openDeadlineCalc(){const sel=document.getElementById('dl_prod');sel.innerHTML='<option value="">선택...</option>'+S.PRODS.map(p=>`<option value="${p.id}">${p.id}</option>`).join('');document.getElementById('dl_due').value=fD(new Date(Date.now()+7*24*3600*1000));openModal('deadlineModal');}

export function calcDeadline(){const prodId=document.getElementById('dl_prod').value;const dueStr=document.getElementById('dl_due').value;if(!prodId||!dueStr){document.getElementById('dl_result').innerHTML='';return;}const prod=S.PRODS.find(p=>p.id===prodId);if(!prod)return;const cat=prod.category;const stack=prod.stackCount||0;const joint=prod.dcJoint||'Brazing';const heat=prod.heatTreat||'N';const routeStr=prod.route||buildRoute(cat,joint,heat);const routeArr=routeStr.split('→').filter(Boolean);const totalDays=routeArr.reduce((s,p)=>s+procDays(p,cat,stack),0);const dueDate=new Date(dueStr);let sd=new Date(dueDate);let remaining=totalDays;while(remaining>0){sd.setDate(sd.getDate()-1);const w=sd.getDay();if(w!==0&&w!==6)remaining--;}const today=new Date();today.setHours(0,0,0,0);const diff=Math.ceil((dueDate-today)/(1000*60*60*24));let urgencyHtml='';if(diff<0)urgencyHtml=`<span class="urgency-badge" style="background:rgba(239,68,68,0.2);color:#ef4444">⛔ 이미 지남</span>`;else if(diff===0)urgencyHtml=`<span class="urgency-badge" style="background:rgba(239,68,68,0.2);color:#ef4444">🔴 오늘 납기</span>`;else if(diff<=3)urgencyHtml=`<span class="urgency-badge" style="background:rgba(245,158,11,0.2);color:#f59e0b">🟡 긴급 (${diff}일)</span>`;else urgencyHtml=`<span class="urgency-badge" style="background:rgba(16,185,129,0.2);color:#10b981">🟢 여유 (${diff}일)</span>`;let tableRows='';let cum=0;routeArr.forEach(p=>{const days=procDays(p,cat,stack);const ps=addBD(new Date(sd),cum);const pe=addBD(new Date(ps),days);tableRows+=`<tr><td style="color:${PROC_COLORS[p]}">${p}</td><td>${fD(ps)}</td><td>${fD(pe)}</td><td>${days}일</td></tr>`;cum+=days;});S.setDlData({startDate:fD(sd),dueDate:dueStr,prodId,routeArr,totalDays});document.getElementById('dl_snBtn').style.display='';document.getElementById('dl_result').innerHTML=`<div style="display:flex;gap:16px;flex-wrap:wrap;margin-bottom:12px;font-size:13px"><div><span style="color:var(--t2)">투입일:</span> <strong>${fD(sd)}</strong></div><div><span style="color:var(--t2)">납기일:</span> <strong>${dueStr}</strong></div><div><span style="color:var(--t2)">총 소요일:</span> <strong>${totalDays}일</strong></div><div>${urgencyHtml}</div></div><div class="table-wrap deadline-table"><table><thead><tr><th>공정</th><th>시작일</th><th>완료예정</th><th>소요일</th></tr></thead><tbody>${tableRows}</tbody></table></div>`;}

export function deadlineToSN(){if(!S.dlData)return;closeModal('deadlineModal');openSNModal();document.getElementById('sn_prod').value=S.dlData.prodId;document.getElementById('sn_start').value=S.dlData.startDate;onSNProdChange();}

export function openIssueModal(snVal){document.getElementById('is_date').value=fD(new Date());document.getElementById('is_type').value='메모';document.getElementById('is_content').value='';const sel=document.getElementById('is_prod');sel.innerHTML='<option value="">선택...</option>'+S.PRODS.map(p=>`<option value="${p.id}">${p.id}</option>`).join('');if(snVal){const item=S.D.find(d=>d.sn===snVal);if(item)sel.value=item.productName||'';loadIssueSNList();document.getElementById('is_sn').value=snVal;}else{document.getElementById('is_sn').value='';}openModal('issueModal');}
export function loadIssueSNList(){const prod=document.getElementById('is_prod').value;const sns=S.D.filter(d=>d.productName===prod).map(d=>d.sn);document.getElementById('issueSNList').innerHTML=sns.map(s=>`<option value="${s}">`).join('');}
export async function saveIssue(){const content=document.getElementById('is_content').value.trim();if(!content){toast('내용을 입력하세요','err');return;}await addDoc(collection(db,'issues'),{date:document.getElementById('is_date').value,productName:document.getElementById('is_prod').value,sn:document.getElementById('is_sn').value,content,type:document.getElementById('is_type').value,createdAt:serverTimestamp(),createdBy:S.currentUser?.email||''});toast('이슈 등록 완료','ok');closeModal('issueModal');}

export function openReportModal(){const today=fD(new Date());const todayDone=S.D.filter(d=>{const procs=d.processes||{};return Object.values(procs).some(p=>p.actualEnd===today&&p.status==='완료');});const todayStart=S.D.filter(d=>d.startDate===today);const late=S.D.filter(d=>d.status==='지연');const todayIssues=S.ISSUES.filter(i=>i.date===today);const prog=S.D.filter(d=>d.status==='진행');const defectCount=S.D.filter(d=>d.status==='폐기'||d.defectType==='NG').length;const{PROC_ORDER}=require('./constants.js');const procSummary=PROC_ORDER.map(p=>{const cnt=S.D.filter(d=>(d.processes||{})[p]?.status==='진행').length;return cnt>0?`  ${p}: ${cnt}건 진행중`:null;}).filter(Boolean).join('\n');const report=`══════════════════════════════\n  📋 ESC 일일 생산 보고서\n  날짜: ${today}\n══════════════════════════════\n\n【 오늘 요약 】\n- 전체: ${S.D.length}건 | 진행: ${prog.length}건\n- 오늘 투입: ${todayStart.length}건 | 공정완료: ${todayDone.length}건\n- 지연: ${late.length}건 | 불량: ${defectCount}건\n\n【 공정별 】\n${procSummary||'  없음'}\n\n【 지연 건 】\n${late.length?late.map(d=>`  - ${d.sn} (${d.productName})`).join('\n'):'  없음'}\n\n══════════════════════════════`;document.getElementById('reportContent').textContent=report;openModal('reportModal');}

export function copyReport(){navigator.clipboard.writeText(document.getElementById('reportContent').textContent).then(()=>toast('복사 완료','ok'));}

export function openWidgetSettings(){renderWidgetSettingsList();openModal('widgetModal');}
function renderWidgetSettingsList(){const list=document.getElementById('widgetSettingsList');const sorted=[...S.widgetConfig].sort((a,b)=>a.order-b.order);list.innerHTML=sorted.map((w,i)=>`<div class="widget-item" data-wid="${w.id}"><div class="toggle ${w.enabled?'on':''}" onclick="toggleWidgetEnabled('${w.id}')"></div><div class="wi-name">${w.label}</div><div class="wi-arrows"><button onclick="moveWidget('${w.id}',-1)" ${i===0?'disabled':''}>▲</button><button onclick="moveWidget('${w.id}',1)" ${i===sorted.length-1?'disabled':''}>▼</button></div></div>`).join('');}
export function toggleWidgetEnabled(id){const w=S.widgetConfig.find(x=>x.id===id);if(w){w.enabled=!w.enabled;renderWidgetSettingsList();}}
export function moveWidget(id,dir){const sorted=[...S.widgetConfig].sort((a,b)=>a.order-b.order);const idx=sorted.findIndex(x=>x.id===id);const swapIdx=idx+dir;if(swapIdx<0||swapIdx>=sorted.length)return;const tmp=sorted[idx].order;sorted[idx].order=sorted[swapIdx].order;sorted[swapIdx].order=tmp;S.setWidgetConfig(sorted);renderWidgetSettingsList();}
export function saveWidgetConfig(){localStorage.setItem('esc_widget_config',JSON.stringify(S.widgetConfig));toast('위젯 설정 저장','ok');closeModal('widgetModal');import('./home.js').then(h=>h.renderHome());}
export function resetWidgetConfig(){const{DEFAULT_WIDGETS}=require('./constants.js');S.setWidgetConfig(JSON.parse(JSON.stringify(DEFAULT_WIDGETS)));renderWidgetSettingsList();toast('기본값 초기화','ok');}
export function saveGeminiKey(){const key=document.getElementById('geminiKeyInput').value.trim();if(!key){toast('API Key를 입력하세요','warn');return;}localStorage.setItem('geminiKey',key);document.getElementById('geminiKeyStatus').textContent='✅ 저장됨';toast('Gemini API Key 저장','ok');}
